// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Insight = Collections['insights']['schema']['_output']
export declare const insights: Insight[]

export type Memo = Collections['memos']['schema']['_output']
export declare const memos: Memo[]
